# -*- coding: utf-8 -*-
"""pilot cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RFNwDbzsb-eo2KYLOlSvACB-oX9T_w-X
"""

from flask import Flask, request, render_template
import numpy as np
from PIL import Image, ImageChops, ImageEnhance
import os
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Dense, Flatten, Dropout

app = Flask(__name__)

def define_model():
    model = Sequential([
        Conv2D(32, (5, 5), activation='relu', input_shape=(128, 128, 3)),
        Conv2D(32, (5, 5), activation='relu'),
        MaxPool2D((2, 2)),
        Dropout(0.25),
        Flatten(),
        Dense(256, activation='relu'),
        Dropout(0.5),
        Dense(2, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

model = define_model()
# Ensure you update this path to the correct location of your model weights
model.load_weights("/content/cnn_pilot_saving_model.h5") # Update the path as needed

def convert_to_ela_image(image_path, quality=90):
    temp_file = 'temp.jpg'
    original = Image.open(image_path).convert('RGB')
    original.save(temp_file, 'JPEG', quality=quality)

    saved = Image.open(temp_file)
    diff = ImageChops.difference(original, saved)
    max_diff = max([ex[1] for ex in diff.getextrema()])
    scale = 255.0 / max_diff

    ela_image = ImageEnhance.Brightness(diff).enhance(scale)
    os.remove(temp_file)
    return ela_image

def prepare_image(image_path):
    image = convert_to_ela_image(image_path).resize((128, 128))
    image = np.array(image).flatten() / 255.0
    return image.reshape(-1, 128, 128, 3)

@app.route('/')
def upload_file():
    return render_template('upload.html')

@app.route('/uploader', methods=['POST'])
def upload_image():
    if 'file' not in request.files:
        return 'No file part'

    file = request.files['file']
    if file.filename == '':
        return 'No selected file'

    image_path = os.path.join('uploads', file.filename)
    file.save(image_path)

    image = prepare_image(image_path)
    prediction = model.predict(image)
    predicted_class = np.argmax(prediction, axis=1)[0]
    result = "Real Image" if predicted_class == 1 else "Fake Image"

    os.remove(image_path)
    return result

if __name__ == '__main__':
    app.run(debug=True)

from google.colab import drive
drive.mount('/content/drive')